### ISSUE TITLE
Include files not working in toml config

### ISSUE THREAD

**Issue by tcerqueira** [cargo-lambda/cargo-lambda#781]
# Description

When adding `include = [ "config/" ]` to the toml file it doesn't include in the final `zip` file. When using through the cli with the `--include` flag it properly includes. On the logs it correctly detects there are files to include.

I also use `env` and `tags` configuration in the toml and those seem to be working fine.

PS: I'm also running in `--dry` mode.

**Comment by calavera** [comment]
Thanks for opening this issue. Can you share a full example of the configuration file you’re using, so I can validate a proper fix? Knowing the Cargo Lambda version you’re using would also be helpful to ensure it’s not already been resolved in the latest one.

**Comment by tcerqueira** [comment]
Sorry for the late response. At the moment, my configuration is a workaround but I'll share it.
```rs
// package Cargo.toml inside a workspace
[package.metadata.lambda.deploy]
env = { "APP_ENVIRONMENT" = "production" }
tags = { "organization" = "gotcha" }
```
```rs
// config.toml
[alias]
build-lambda = "lambda build --release --arm64 --features aws-lambda"
deploy-lambda = "lambda deploy --include dist/ --include config/"
```
I was on `1.3.0` but updated to `1.6.3`, didn't seem to fix it. Upon further debugging I take back that the rest of the configuration is working fine, the `env` and `tags` are also not set, although they are correctly read.

The project is a little big so it's hard to provide a working example but if you want me to try and test something just ask.

**Comment by calavera** [comment]
That’s interesting, I wonder if this is a consequence of using aliases and workspaces mixed together.

I’m currently on a trip without a laptop to test this until next week. I’ll try to reproduce the issue when I’m back home.

**Comment by calavera** [comment]
Hi @tcerqueira, thanks for your patience with this issue. Unfortunately, I'm not able to reproduce your problem. I've added some tests that verify that things are working as expected in https://github.com/cargo-lambda/cargo-lambda/pull/792.

I've also recorded a video where the configuration is read correctly from the function's manifest. Can you check and tell me if your setup is any different at all? I've also tried calling the command with Cargo aliases with the same result:

https://github.com/user-attachments/assets/a1f9ad3c-29e8-4baa-bffd-a05f15240005

**Comment by tcerqueira** [comment]
I've tried your demo locally with my project, and I forgot that in my CI I add the flags `--env-var` to inject a bunch of database secrets. That works and I hypothesized that it was overriding other configuration sources, but I tried the simplest `cargo lambda deploy` and it's still not loading them, so that doesn't seem to be it.

Only difference I see, is that my package name is not the same as the folder. `/server` -> `gotcha-server` package name.

**Comment by calavera** [comment]
> Only difference I see, is that my package name is not the same as the folder. `/server` -> `gotcha-server` package name.

Let me revisit the logic that detects how metadata is loaded, that could be what’s causing this issue.

**Comment by calavera** [comment]
that doesn't seem to matter since the metadata is loaded based on the package name regardless the folder name. Here's a screenshot with what I believe is your configuration, where the package name is `fun1`, and the directory name is `function1`:

![Image](https://github.com/user-attachments/assets/0fa38004-b605-49c7-903a-a640bea6ebc9)

**Comment by tcerqueira** [comment]
I think I found the issue, I tried creating a workspace from scratch and keep adding things to the project structure until it breaks. I found that when I add a proc-macro crate it stops working. To recap my full configuration: a workspace with 2 crates, one binary and one proc-macro, a build script on the binary crate.

**Comment by calavera** [comment]
ohhh that’s interesting, thanks for diving deep into this problem. I’ll try to replicate this myself now that I have this information

**Comment by calavera** [comment]
I finally managed to reproduce the problem 🎊 #796 should solve the problem.

**Comment by calavera** [comment]
I'll release a new version with this fix on Monday or Tuesday.

**Comment by calavera** [comment]
Fix released in version [1.7.0](https://github.com/cargo-lambda/cargo-lambda/releases/tag/v1.7.0)
